//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.07 at 10:09:53 PM GMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "https://t4is.uv.mx/saludos", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package https.t4is_uv_mx.saludos;
